language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 1.0.4
branches:
  only:
    - master
    - develop
before_script:
  - chmod a+x ./travis-build.sh
  - chmod a+x ./after-success.sh
  - chmod a+x ./scripts/dotnet-restore.sh
  - chmod a+x ./scripts/dotnet-build.sh
script:
  - ./travis-build.sh
after_success:
  - ./after-success.sh
notifications:
  email:
    on_success: never
    on_failure: always
